FROM python:3.7
RUN apt-get update 
RUN apt-get -y install python3-flask-sqlalchemy python3-psycopg2
RUN mkdir app
COPY . /app
WORKDIR /app
RUN pip install --no-cache-dir -r requirements.txt
ENV FLASK_APP=app.py
ENV FLASK_ENV=development
EXPOSE 5000
ENTRYPOINT [ "python" ]
CMD [ "app.py" ]
